{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
type: kubernetes.io/tls
data:
  {{- $cert := genSelfSignedCert "api.local" nil nil 365 }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
---
{{- end }}
{{- end }}