name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout коду
        uses: actions/checkout@v4

      # Переходимо в папку backend і збираємо образ локально
      - name: Збірка Docker образу
        run: |
          cd backend
          docker build -t backend-api:latest .

      # Оновлюємо наш додаток в Kubernetes через Helm
      - name: Деплой через Helm-чарт
        run: |
          helm upgrade --install my-release my-app-chart --set image.repository=backend-api --set image.tag=latest